/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.estacio.mei.visao.contas.receber;

import br.estacio.mei.dao.VendaDao;
import br.estacio.mei.dao.implementacao.VendaDaoEstatica;
import br.estacio.mei.exemplo.Aluno;
import br.estacio.mei.model.Cliente;
import br.estacio.mei.model.Venda;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aluno
 */
public class ContasAReceberPrincipal extends javax.swing.JPanel {
    VendaDao vendaDao = new VendaDaoEstatica();
    /**
     * Creates new form ContasAReceberPrincipal
     */
    public ContasAReceberPrincipal() {
        initComponents();
        initVendasFake();
        populaTabela();
    }

    private void initVendasFake(){
        Cliente cliente = new Cliente();
        cliente.setNome("Teste");
        Venda venda = new Venda();
        venda.setCliente(cliente);
        venda.setObservacao(" Nenhuma");
        venda.setFormaPagamento("Prazo");
        venda.setValor(2000);
        
        vendaDao.salvarVenda(venda);
        
        vendaDao.finalizarVendaAPrazo(venda);
        
    }
    public void addLinhaNaTabela(Venda venda) {
        DefaultTableModel model = (DefaultTableModel) tbConsultaReceber.getModel();
        
        System.out.println(venda);
        
        Object rowData[] = new Object[6];
        rowData[0] = venda.getCliente().getNome();
        rowData[1] = venda.getCodigo();
        rowData[2] = venda.getFormaPagamento();
        rowData[3] = venda.getValor();
        rowData[4] = venda.getData();
        rowData[5] = venda.getStatus();

        model.addRow(rowData);
    }

    public void populaTabela() {

        
        ArrayList<Venda> lista = vendaDao.listarVendasAPrazo();

        for (int i = 0; i < lista.size(); i++) {
            addLinhaNaTabela(lista.get(i));
        }
        tbConsultaReceber.repaint();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sl_status_consulta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tx_cod_venda_consulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_cliente_consulta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaReceber = new javax.swing.JTable();
        ef_baixa_consulta = new javax.swing.JButton();
        al_venda_consulta = new javax.swing.JButton();
        rl_mensal_consulta = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(970, 470));
        setMinimumSize(new java.awt.Dimension(970, 470));
        setPreferredSize(new java.awt.Dimension(970, 470));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1305, 105));
        jPanel1.setMinimumSize(new java.awt.Dimension(1305, 105));
        jPanel1.setPreferredSize(new java.awt.Dimension(1305, 105));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Contas a Receber");

        sl_status_consulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Aberto", "A Receber", "Baixado", "Cancelado" }));
        sl_status_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_status_consultaActionPerformed(evt);
            }
        });

        jLabel2.setText("Status");

        tx_cod_venda_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_cod_venda_consultaActionPerformed(evt);
            }
        });

        jLabel3.setText("Cod. Venda");

        jLabel4.setText("Cliente");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Data Venda");

        jLabel6.setText("Funcionario");

        jButton4.setText("Pesquisa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sl_status_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_cod_venda_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tx_cliente_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sl_status_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_cod_venda_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_cliente_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        tbConsultaReceber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Cod. Venda", "Forma Pagamento", "Valor", "Data Venda", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbConsultaReceber);

        ef_baixa_consulta.setText("Efetuar Baixa");
        ef_baixa_consulta.setMaximumSize(new java.awt.Dimension(123, 59));
        ef_baixa_consulta.setMinimumSize(new java.awt.Dimension(123, 59));
        ef_baixa_consulta.setPreferredSize(new java.awt.Dimension(123, 59));
        ef_baixa_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ef_baixa_consultaActionPerformed(evt);
            }
        });

        al_venda_consulta.setText("Alterar Venda");
        al_venda_consulta.setMaximumSize(new java.awt.Dimension(123, 59));
        al_venda_consulta.setMinimumSize(new java.awt.Dimension(123, 59));
        al_venda_consulta.setPreferredSize(new java.awt.Dimension(123, 59));
        al_venda_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                al_venda_consultaActionPerformed(evt);
            }
        });

        rl_mensal_consulta.setText("Relatório Mensal");
        rl_mensal_consulta.setMaximumSize(new java.awt.Dimension(123, 59));
        rl_mensal_consulta.setMinimumSize(new java.awt.Dimension(123, 59));
        rl_mensal_consulta.setPreferredSize(new java.awt.Dimension(123, 59));
        rl_mensal_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rl_mensal_consultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(al_venda_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ef_baixa_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rl_mensal_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ef_baixa_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(al_venda_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rl_mensal_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ef_baixa_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ef_baixa_consultaActionPerformed
        ContasAReceberBaixa painel = new ContasAReceberBaixa();
        painel.setVisible(true);
        
    }//GEN-LAST:event_ef_baixa_consultaActionPerformed

    private void sl_status_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_status_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl_status_consultaActionPerformed

    private void tx_cod_venda_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_cod_venda_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_cod_venda_consultaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void al_venda_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_al_venda_consultaActionPerformed
       ContasAReceberAlterar painel = new ContasAReceberAlterar();
        painel.setVisible(true);
    }//GEN-LAST:event_al_venda_consultaActionPerformed

    private void rl_mensal_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rl_mensal_consultaActionPerformed
        ContasAReceberRelatorio painel = new ContasAReceberRelatorio();
        painel.setVisible(true);
    }//GEN-LAST:event_rl_mensal_consultaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton al_venda_consulta;
    private javax.swing.JButton ef_baixa_consulta;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton rl_mensal_consulta;
    private javax.swing.JComboBox<String> sl_status_consulta;
    private javax.swing.JTable tbConsultaReceber;
    private javax.swing.JTextField tx_cliente_consulta;
    private javax.swing.JTextField tx_cod_venda_consulta;
    // End of variables declaration//GEN-END:variables
}

