/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.estacio.mei.visao.vendas;

import static br.estacio.mei.visao.vendas.VendaPrincipal.gbFormaPagamento;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia TOPz
 */
public class vendaFinalizada extends javax.swing.JDialog {

    /**
     * Creates new form vendaFinalizada
     * @param parent
     * @param modal
     */
    public vendaFinalizada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vendaSucesso = new javax.swing.JPanel();
        lblSucesso = new javax.swing.JLabel();
        btnEnd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSucesso.setText("Parabens! Sua venda Foi Finalizada");

        btnEnd.setText("OK");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vendaSucessoLayout = new javax.swing.GroupLayout(vendaSucesso);
        vendaSucesso.setLayout(vendaSucessoLayout);
        vendaSucessoLayout.setHorizontalGroup(
            vendaSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendaSucessoLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(lblSucesso)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(vendaSucessoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vendaSucessoLayout.setVerticalGroup(
            vendaSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendaSucessoLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblSucesso)
                .addGap(18, 18, 18)
                .addComponent(btnEnd)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(vendaSucesso, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        // TODO add your handling code here:
        VendaPrincipal.txtDescADD.setText("Ex: Aqui pode colocar as informações adicionais!");
        VendaPrincipal.txtQtd.setText("Ex: 00");
        VendaPrincipal.txtValor.setText("1.00");
        VendaPrincipal.lblValor.setText("00,00");
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Selecione Um Cliente");
        VendaPrincipal.jcNome.setModel(model);
        
        DefaultComboBoxModel modelProduto = new DefaultComboBoxModel();
        modelProduto.addElement("Selecione Um Produto");
        VendaPrincipal.jcProduto.setModel(modelProduto);

        DefaultTableModel dtm = (DefaultTableModel) VendaPrincipal.tbProdutos.getModel();
        dtm.setRowCount(0);
        
        VendaPrincipal.gbFormaPagamento.clearSelection();
        dispose();
    }//GEN-LAST:event_btnEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendaFinalizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendaFinalizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendaFinalizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendaFinalizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vendaFinalizada dialog = new vendaFinalizada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JLabel lblSucesso;
    private javax.swing.JPanel vendaSucesso;
    // End of variables declaration//GEN-END:variables
}
