/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.estacio.mei.visao.vendas;

import br.estacio.mei.dao.ClienteDao;
import br.estacio.mei.dao.ProdutoDao;
import br.estacio.mei.dao.VendaDao;
import br.estacio.mei.dao.implementacao.ClienteDaoEstatico;
import br.estacio.mei.dao.implementacao.ProdutoDaoEstatico;
import br.estacio.mei.dao.implementacao.VendaDaoEstatica;
import br.estacio.mei.model.Cliente;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import br.estacio.mei.model.ItemVenda;
import br.estacio.mei.model.Produto;
import br.estacio.mei.model.Venda;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia TOPz
 */
public class VendaPrincipal extends javax.swing.JPanel {

    VendaDao vendaDao = new VendaDaoEstatica();
    Venda vendaAtual = null;
    
    ClienteDao clienteDao = new ClienteDaoEstatico();
    
    ProdutoDao produtoDao = new ProdutoDaoEstatico();
    
    /**
     * Creates new form backup
     */
    public VendaPrincipal() {
        initComponents();
        initComboCliente();
        initComboProduto();
    }
    
    private void initComboCliente(){
        Object cliente[] = clienteDao.buscarClientes().toArray();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Selecione Um Cliente");
        for(int i = 0; i<cliente.length; i++){
            model.addElement(cliente[i]);
        }
        jcNome.setModel(model);
    }
    
    private void initComboProduto(){
        Object produto[] = produtoDao.pesquisarPorNome(toString()).toArray();
        DefaultComboBoxModel modelProduto = new DefaultComboBoxModel();
        modelProduto.addElement("Selecione Um Produto");
        for(int i = 0; i<produto.length; i++){
            modelProduto.addElement(produto[i]);
        }
       jcProduto.setModel(modelProduto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbFormaPagamento = new javax.swing.ButtonGroup();
        vendasPainel = new javax.swing.JPanel();
        painelInicio = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        lblQtd = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblVal = new javax.swing.JLabel();
        btnAddProduto = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        lblDataVenda = new javax.swing.JLabel();
        jcNome = new javax.swing.JComboBox<>();
        jcProduto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        painelMeio = new javax.swing.JPanel();
        tblProdutos = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        jpTotal = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        lblSifrao = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        painelFim = new javax.swing.JPanel();
        jspDescricao = new javax.swing.JScrollPane();
        txtDescADD = new javax.swing.JTextArea();
        lblDescADD = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        jrbDinheiro = new javax.swing.JRadioButton();
        jrbCredito = new javax.swing.JRadioButton();
        jrbDebito = new javax.swing.JRadioButton();
        lblMeioPagamento = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        vendasPainel.setLayout(new java.awt.BorderLayout());

        painelInicio.setBackground(new java.awt.Color(153, 255, 255));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome do Cliente (Opicional) :");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 0));
        lblDescricao.setText("Descrição :");

        txtQtd.setBackground(new java.awt.Color(255, 255, 255));
        txtQtd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtQtd.setForeground(new java.awt.Color(0, 0, 0));
        txtQtd.setText("Ex: 00");

        lblQtd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQtd.setForeground(new java.awt.Color(0, 0, 0));
        lblQtd.setText("Qtd. :");

        txtValor.setBackground(new java.awt.Color(102, 102, 102));
        txtValor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtValor.setForeground(new java.awt.Color(255, 255, 255));
        txtValor.setText("0.00");

        lblVal.setForeground(new java.awt.Color(0, 0, 0));
        lblVal.setText("Valor (u):");

        btnAddProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddProduto.setForeground(new java.awt.Color(0, 0, 0));
        btnAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Incluir_black.png"))); // NOI18N
        btnAddProduto.setText("Add");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        lblData.setForeground(new java.awt.Color(0, 0, 0));
        lblData.setText("Data: ");

        lblDataVenda.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDataVenda.setForeground(new java.awt.Color(0, 0, 0));

        jcNome.setBackground(new java.awt.Color(255, 255, 255));
        jcNome.setForeground(new java.awt.Color(0, 0, 0));
        jcNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcProduto.setBackground(new java.awt.Color(255, 255, 255));
        jcProduto.setForeground(new java.awt.Color(0, 0, 0));
        jcProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cesta-de-la-compra-simbolo-en-movimiento.png"))); // NOI18N

        javax.swing.GroupLayout painelInicioLayout = new javax.swing.GroupLayout(painelInicio);
        painelInicio.setLayout(painelInicioLayout);
        painelInicioLayout.setHorizontalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(lblNome)
                    .addComponent(jcNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInicioLayout.createSequentialGroup()
                        .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtd))
                        .addGap(18, 18, 18)
                        .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVal)
                            .addGroup(painelInicioLayout.createSequentialGroup()
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddProduto))))
                    .addComponent(lblData)
                    .addComponent(lblDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelInicioLayout.setVerticalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInicioLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(painelInicioLayout.createSequentialGroup()
                        .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblData)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcNome)
                            .addComponent(lblDataVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQtd)
                            .addGroup(painelInicioLayout.createSequentialGroup()
                                .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricao)
                                    .addComponent(lblVal, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18))
        );

        txtQtd .addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtQtd .getText().equals("Ex: 00")) {
                    txtQtd .setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (txtQtd .getText().isEmpty()) {
                    txtQtd .setText("Ex: 00");
                }
            }
        });
        txtValor.setEditable(false);
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lblDataVenda.setText(formato.format(dataSistema));

        vendasPainel.add(painelInicio, java.awt.BorderLayout.PAGE_START);

        painelMeio.setBackground(new java.awt.Color(153, 255, 255));
        painelMeio.setMinimumSize(new java.awt.Dimension(100, 200));
        painelMeio.setPreferredSize(new java.awt.Dimension(453, 200));
        painelMeio.setLayout(new java.awt.BorderLayout());

        tblProdutos.setBackground(new java.awt.Color(0, 0, 0));
        tblProdutos.setForeground(new java.awt.Color(255, 255, 255));

        tbProdutos.setBackground(new java.awt.Color(255, 255, 255));
        tbProdutos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tbProdutos.setForeground(new java.awt.Color(0, 0, 0));
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Valor"
            }
        ));
        tbProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbProdutos.setFocusable(false);
        tbProdutos.setGridColor(new java.awt.Color(255, 255, 255));
        tbProdutos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbProdutos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblProdutos.setViewportView(tbProdutos);

        painelMeio.add(tblProdutos, java.awt.BorderLayout.CENTER);

        jpTotal.setBackground(new java.awt.Color(153, 255, 255));
        jpTotal.setPreferredSize(new java.awt.Dimension(934, 40));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("Valor :");

        lblSifrao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSifrao.setForeground(new java.awt.Color(0, 0, 0));
        lblSifrao.setText("R$ ");

        lblValor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValor.setForeground(new java.awt.Color(0, 0, 0));
        lblValor.setText("00,00");

        javax.swing.GroupLayout jpTotalLayout = new javax.swing.GroupLayout(jpTotal);
        jpTotal.setLayout(jpTotalLayout);
        jpTotalLayout.setHorizontalGroup(
            jpTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTotalLayout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSifrao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValor)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jpTotalLayout.setVerticalGroup(
            jpTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblValor)
                    .addComponent(lblSifrao))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        painelMeio.add(jpTotal, java.awt.BorderLayout.PAGE_END);

        vendasPainel.add(painelMeio, java.awt.BorderLayout.CENTER);

        painelFim.setBackground(new java.awt.Color(153, 255, 255));
        painelFim.setPreferredSize(new java.awt.Dimension(934, 200));

        jspDescricao.setPreferredSize(new java.awt.Dimension(223, 50));

        txtDescADD.setBackground(new java.awt.Color(255, 255, 255));
        txtDescADD.setColumns(20);
        txtDescADD.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescADD.setForeground(new java.awt.Color(0, 0, 0));
        txtDescADD.setRows(5);
        txtDescADD.setText("Ex: Aqui pode colocar as informações adicionais!");
        txtDescADD.setMinimumSize(new java.awt.Dimension(223, 45));
        txtDescADD.setPreferredSize(new java.awt.Dimension(223, 45));
        jspDescricao.setViewportView(txtDescADD);
        txtDescADD .addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtDescADD .getText().equals("Ex: Aqui pode colocar as informações adicionais!")) {
                    txtDescADD .setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (txtDescADD .getText().isEmpty()) {
                    txtDescADD .setText("Ex: Aqui pode colocar as informações adicionais!");
                }
            }
        });

        lblDescADD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescADD.setForeground(new java.awt.Color(0, 0, 0));
        lblDescADD.setText("Observação: ");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirm.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        gbFormaPagamento.add(jrbDinheiro);
        jrbDinheiro.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jrbDinheiro.setForeground(new java.awt.Color(0, 0, 0));
        jrbDinheiro.setText("Dinheiro");

        gbFormaPagamento.add(jrbCredito);
        jrbCredito.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jrbCredito.setForeground(new java.awt.Color(0, 0, 0));
        jrbCredito.setText("Cartão de Crédito");

        gbFormaPagamento.add(jrbDebito);
        jrbDebito.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jrbDebito.setForeground(new java.awt.Color(0, 0, 0));
        jrbDebito.setText("Cartão de Débito");

        lblMeioPagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMeioPagamento.setForeground(new java.awt.Color(0, 0, 0));
        lblMeioPagamento.setText("Meio de Pagamento : ");

        javax.swing.GroupLayout painelFimLayout = new javax.swing.GroupLayout(painelFim);
        painelFim.setLayout(painelFimLayout);
        painelFimLayout.setHorizontalGroup(
            painelFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFimLayout.createSequentialGroup()
                        .addComponent(lblDescADD)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jspDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelFimLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblMeioPagamento)
                        .addGap(18, 18, 18)
                        .addGroup(painelFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbCredito)
                            .addComponent(jrbDinheiro)
                            .addGroup(painelFimLayout.createSequentialGroup()
                                .addComponent(jrbDebito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addComponent(btnCancelar)
                                .addGap(62, 62, 62)
                                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        painelFimLayout.setVerticalGroup(
            painelFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescADD)
                .addGap(3, 3, 3)
                .addComponent(jspDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbDinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDebito)
                    .addComponent(lblMeioPagamento)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbCredito)
                .addGap(26, 26, 26))
        );

        vendasPainel.add(painelFim, java.awt.BorderLayout.PAGE_END);

        add(vendasPainel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        // TODO add your handling code here:
        if (vendaAtual == null) {
            Cliente cliente = new Cliente();
            if(jcNome.getSelectedItem() instanceof Cliente){
                cliente = (Cliente) jcNome.getSelectedItem();
            }

            Venda venda = new Venda();
            venda.setCliente(cliente);
            venda.setUsuario(null);

            vendaAtual = vendaDao.salvarVenda(venda);

        }
        Produto produto = new Produto();
        produto.setDescricao(jcProduto.getSelectedItem().toString());
        produto.setPrecoVenda(Double.parseDouble(txtValor.getText()));

        ItemVenda itemVenda = new ItemVenda();
        itemVenda.setQuantidade(Integer.parseInt(txtQtd.getText()));
        itemVenda.setValor(Double.parseDouble(txtValor.getText()));
        itemVenda.setProduto(produto);
        
        itemVenda.setVenda(vendaAtual);
        itemVenda = vendaDao.salvarItemVenda(itemVenda);

        DefaultTableModel dtm = (DefaultTableModel) tbProdutos.getModel();
        dtm.addRow(new Object[]{itemVenda.getCodigo(),itemVenda.getProduto().getNome(), itemVenda.getQuantidade(), itemVenda.getValor()});

        txtQtd.setText("Ex: 00");
        
        lblValor.setText("" + vendaDao.valorTotal(vendaAtual));
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        if (jrbCredito.isSelected()) {
            vendaFinalizada vendaFinalizada = new vendaFinalizada(new javax.swing.JFrame(), true);
            vendaFinalizada.setLocationRelativeTo(this);
            vendaFinalizada.setVisible(true);
            
        } else if(jrbDebito.isSelected()){ 
            vendaFinalizada vendaFinalizada = new vendaFinalizada(new javax.swing.JFrame(), true);
            vendaFinalizada.setLocationRelativeTo(this);
            vendaFinalizada.setVisible(true);
                       
        }else if(jrbDinheiro.isSelected()){
            vendaFinalizada vendaFinalizada = new vendaFinalizada(new javax.swing.JFrame(), true);
            vendaFinalizada.setLocationRelativeTo(this);
            vendaFinalizada.setVisible(true);
            
        }else{
           erroPagamento erroPagamento = new erroPagamento(new javax.swing.JFrame(), true);
           erroPagamento.setLocationRelativeTo(this);
           erroPagamento.setVisible(true); 
        }
        
        vendaAtual.setStatus(1);
        vendaDao.atualizarVenda(vendaAtual);

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtDescADD.setText("Ex: Aqui pode colocar as informações adicionais!");
        txtQtd.setText("Ex: 00");
        lblValor.setText("00,00");
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Selecione Um Cliente");
        jcNome.setModel(model);
        
        DefaultComboBoxModel modelProduto = new DefaultComboBoxModel();
        modelProduto.addElement("Selecione Um Produto");
        jcProduto.setModel(modelProduto);

        DefaultTableModel dtm = (DefaultTableModel) tbProdutos.getModel();
        dtm.setRowCount(0);
        
        gbFormaPagamento.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    protected static javax.swing.ButtonGroup gbFormaPagamento;
    private javax.swing.JLabel jLabel1;
    protected static javax.swing.JComboBox<String> jcNome;
    protected static javax.swing.JComboBox<String> jcProduto;
    private javax.swing.JPanel jpTotal;
    private javax.swing.JRadioButton jrbCredito;
    private javax.swing.JRadioButton jrbDebito;
    private javax.swing.JRadioButton jrbDinheiro;
    private javax.swing.JScrollPane jspDescricao;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataVenda;
    private javax.swing.JLabel lblDescADD;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblMeioPagamento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblSifrao;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVal;
    protected static javax.swing.JLabel lblValor;
    private javax.swing.JPanel painelFim;
    private javax.swing.JPanel painelInicio;
    private javax.swing.JPanel painelMeio;
    protected static javax.swing.JTable tbProdutos;
    private javax.swing.JScrollPane tblProdutos;
    protected static javax.swing.JTextArea txtDescADD;
    protected static javax.swing.JTextField txtQtd;
    protected static javax.swing.JTextField txtValor;
    private javax.swing.JPanel vendasPainel;
    // End of variables declaration//GEN-END:variables
}
