/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.estacio.mei.visao.login;


import br.estacio.mei.model.Usuario;
import br.estacio.mei.visao.categoria.CategoriaPrincipal;
import br.estacio.mei.visao.cliente.ClientePrincipal;
import br.estacio.mei.visao.compras.CompraPrincipal;
import br.estacio.mei.visao.contas.pagar.ContasAPagarPrincipal;
import br.estacio.mei.visao.contas.receber.ContasAReceberPrincipal;
import br.estacio.mei.visao.fornecedor.FornecedorPrincipal;
import br.estacio.mei.visao.produto.ProdutoPrincipal;
import br.estacio.mei.visao.relatorio.estoque.RelatorioDeEstoquePrincipal;
import br.estacio.mei.visao.relatorio.vendas.RelatorioVendasPrincipal;
import br.estacio.mei.visao.sac.SacPrincipal;
import br.estacio.mei.visao.usuario.UsuarioPrincipal;
import br.estacio.mei.visao.vendas.VendaPrincipal;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Marcelo
 */
public class Sistema extends javax.swing.JFrame {

    //private Usuario usuario;

    /**
     * Creates new form Sistema
     */
    public Sistema(Usuario usuario) {
        initComponents();
        panelActive = btnInicio;
        //this.usuario = usuario;
        jlUsuarioLogado.setText(usuario.getUsuario());
    }


    /* Sistema(Usuario usuario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    } */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateral = new javax.swing.JPanel();
        iconeSistema = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        atalhosDoMenu = new javax.swing.JPanel();
        btnInicio = new javax.swing.JPanel();
        imgInicio = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        btnVendas = new javax.swing.JPanel();
        imgVendas = new javax.swing.JLabel();
        lblVendas = new javax.swing.JLabel();
        btnCompras = new javax.swing.JPanel();
        imgCompras = new javax.swing.JLabel();
        lblCompras = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        imgClientes = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        btnProdutos = new javax.swing.JPanel();
        imgCadastroDeProdutos = new javax.swing.JLabel();
        lblCadastroDeProdutos = new javax.swing.JLabel();
        btnCategorias = new javax.swing.JPanel();
        imgCategorias = new javax.swing.JLabel();
        lblCategorias = new javax.swing.JLabel();
        btnFornecedor = new javax.swing.JPanel();
        imgFornecedores = new javax.swing.JLabel();
        lblFornecedores = new javax.swing.JLabel();
        btnContasAReceber = new javax.swing.JPanel();
        imgContasAReceber = new javax.swing.JLabel();
        lblContasAReceber = new javax.swing.JLabel();
        btnContasAPagar = new javax.swing.JPanel();
        imgContasAPagar = new javax.swing.JLabel();
        lblContasAPagar = new javax.swing.JLabel();
        btnRelatorioDeEstoque = new javax.swing.JPanel();
        imgRelatorioDeEstoque1 = new javax.swing.JLabel();
        lblRelatorioDeEstoque1 = new javax.swing.JLabel();
        btnRelatorioDeVendas = new javax.swing.JPanel();
        imgRelatorioDeVendas = new javax.swing.JLabel();
        lblRelatorioDeVendas = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JPanel();
        imgUsuario = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        btnSac = new javax.swing.JPanel();
        imgSac = new javax.swing.JLabel();
        lblSac = new javax.swing.JLabel();
        btnSair = new javax.swing.JPanel();
        imgSair = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        areaDeTrabalho = new javax.swing.JPanel();
        painelBreadcrumb = new javax.swing.JPanel();
        lblBreadcrumb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlUsuarioLogado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblNomeSistema = new javax.swing.JLabel();
        panelDinamic = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jLhora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuLateral.setBackground(new java.awt.Color(12, 197, 205));
        menuLateral.setMinimumSize(new java.awt.Dimension(64, 64));
        menuLateral.setPreferredSize(new java.awt.Dimension(334, 811));
        menuLateral.setLayout(new java.awt.BorderLayout());

        iconeSistema.setBackground(new java.awt.Color(12, 197, 205));
        iconeSistema.setPreferredSize(new java.awt.Dimension(107, 120));
        iconeSistema.setLayout(null);

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Stocks_64px.png"))); // NOI18N
        imgLogo.setMaximumSize(new java.awt.Dimension(64, 44));
        imgLogo.setPreferredSize(new java.awt.Dimension(64, 100));
        iconeSistema.add(imgLogo);
        imgLogo.setBounds(130, 10, 64, 80);
        iconeSistema.add(jSeparator1);
        jSeparator1.setBounds(30, 100, 280, 10);

        menuLateral.add(iconeSistema, java.awt.BorderLayout.PAGE_START);

        atalhosDoMenu.setBackground(new java.awt.Color(12, 197, 205));
        atalhosDoMenu.setLayout(new java.awt.GridLayout(13, 1));

        btnInicio.setBackground(new java.awt.Color(13, 155, 177));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicioMousePressed(evt);
            }
        });

        imgInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Home_25px.png"))); // NOI18N

        lblInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Início");

        javax.swing.GroupLayout btnInicioLayout = new javax.swing.GroupLayout(btnInicio);
        btnInicio.setLayout(btnInicioLayout);
        btnInicioLayout.setHorizontalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgInicio)
                .addGap(20, 20, 20)
                .addComponent(lblInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInicioLayout.setVerticalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnInicio);

        btnVendas.setBackground(new java.awt.Color(12, 180, 206));
        btnVendas.setPreferredSize(new java.awt.Dimension(111, 40));
        btnVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVendasMousePressed(evt);
            }
        });

        imgVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Christmas_Gift_25px_1.png"))); // NOI18N

        lblVendas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVendas.setForeground(new java.awt.Color(255, 255, 255));
        lblVendas.setText("Vendas");

        javax.swing.GroupLayout btnVendasLayout = new javax.swing.GroupLayout(btnVendas);
        btnVendas.setLayout(btnVendasLayout);
        btnVendasLayout.setHorizontalGroup(
            btnVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVendasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgVendas)
                .addGap(20, 20, 20)
                .addComponent(lblVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnVendasLayout.setVerticalGroup(
            btnVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnVendas);

        btnCompras.setBackground(new java.awt.Color(12, 180, 206));
        btnCompras.setPreferredSize(new java.awt.Dimension(111, 40));
        btnCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnComprasMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
        });

        imgCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Buy_25px.png"))); // NOI18N

        lblCompras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCompras.setForeground(new java.awt.Color(255, 255, 255));
        lblCompras.setText("Compras");

        javax.swing.GroupLayout btnComprasLayout = new javax.swing.GroupLayout(btnCompras);
        btnCompras.setLayout(btnComprasLayout);
        btnComprasLayout.setHorizontalGroup(
            btnComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComprasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgCompras)
                .addGap(20, 20, 20)
                .addComponent(lblCompras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnComprasLayout.setVerticalGroup(
            btnComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnCompras);

        btnClientes.setBackground(new java.awt.Color(12, 180, 206));
        btnClientes.setPreferredSize(new java.awt.Dimension(111, 40));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClientesMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
        });

        imgClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Management_25px.png"))); // NOI18N

        lblClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setText("Clientes");

        javax.swing.GroupLayout btnClientesLayout = new javax.swing.GroupLayout(btnClientes);
        btnClientes.setLayout(btnClientesLayout);
        btnClientesLayout.setHorizontalGroup(
            btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgClientes)
                .addGap(20, 20, 20)
                .addComponent(lblClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnClientesLayout.setVerticalGroup(
            btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnClientes);

        btnProdutos.setBackground(new java.awt.Color(12, 180, 206));
        btnProdutos.setPreferredSize(new java.awt.Dimension(111, 40));
        btnProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProdutosMousePressed(evt);
            }
        });

        imgCadastroDeProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Packaging_25px.png"))); // NOI18N

        lblCadastroDeProdutos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCadastroDeProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastroDeProdutos.setText("Produtos");

        javax.swing.GroupLayout btnProdutosLayout = new javax.swing.GroupLayout(btnProdutos);
        btnProdutos.setLayout(btnProdutosLayout);
        btnProdutosLayout.setHorizontalGroup(
            btnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProdutosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgCadastroDeProdutos)
                .addGap(20, 20, 20)
                .addComponent(lblCadastroDeProdutos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnProdutosLayout.setVerticalGroup(
            btnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCadastroDeProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCadastroDeProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnProdutos);

        btnCategorias.setBackground(new java.awt.Color(12, 180, 206));
        btnCategorias.setPreferredSize(new java.awt.Dimension(134, 40));
        btnCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCategoriasMousePressed(evt);
            }
        });

        imgCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Tournament_25px.png"))); // NOI18N

        lblCategorias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCategorias.setForeground(new java.awt.Color(255, 255, 255));
        lblCategorias.setText("Categorias de Produtos");

        javax.swing.GroupLayout btnCategoriasLayout = new javax.swing.GroupLayout(btnCategorias);
        btnCategorias.setLayout(btnCategoriasLayout);
        btnCategoriasLayout.setHorizontalGroup(
            btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCategoriasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgCategorias)
                .addGap(20, 20, 20)
                .addComponent(lblCategorias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnCategoriasLayout.setVerticalGroup(
            btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnCategorias);

        btnFornecedor.setBackground(new java.awt.Color(12, 180, 206));
        btnFornecedor.setPreferredSize(new java.awt.Dimension(111, 40));
        btnFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFornecedorMousePressed(evt);
            }
        });

        imgFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Food_Truck_25px.png"))); // NOI18N

        lblFornecedores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        lblFornecedores.setText("Fornecedor");

        javax.swing.GroupLayout btnFornecedorLayout = new javax.swing.GroupLayout(btnFornecedor);
        btnFornecedor.setLayout(btnFornecedorLayout);
        btnFornecedorLayout.setHorizontalGroup(
            btnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFornecedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgFornecedores)
                .addGap(20, 20, 20)
                .addComponent(lblFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFornecedorLayout.setVerticalGroup(
            btnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblFornecedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnFornecedor);

        btnContasAReceber.setBackground(new java.awt.Color(12, 180, 206));
        btnContasAReceber.setPreferredSize(new java.awt.Dimension(191, 40));
        btnContasAReceber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnContasAReceberMousePressed(evt);
            }
        });

        imgContasAReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Capital_25px.png"))); // NOI18N

        lblContasAReceber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContasAReceber.setForeground(new java.awt.Color(255, 255, 255));
        lblContasAReceber.setText("Contas a Receber");

        javax.swing.GroupLayout btnContasAReceberLayout = new javax.swing.GroupLayout(btnContasAReceber);
        btnContasAReceber.setLayout(btnContasAReceberLayout);
        btnContasAReceberLayout.setHorizontalGroup(
            btnContasAReceberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnContasAReceberLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgContasAReceber)
                .addGap(20, 20, 20)
                .addComponent(lblContasAReceber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnContasAReceberLayout.setVerticalGroup(
            btnContasAReceberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgContasAReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblContasAReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnContasAReceber);

        btnContasAPagar.setBackground(new java.awt.Color(12, 180, 206));
        btnContasAPagar.setPreferredSize(new java.awt.Dimension(171, 40));
        btnContasAPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnContasAPagarMousePressed(evt);
            }
        });

        imgContasAPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Merchant_Account_25px_1.png"))); // NOI18N

        lblContasAPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContasAPagar.setForeground(new java.awt.Color(255, 255, 255));
        lblContasAPagar.setText("Contas a Pagar");

        javax.swing.GroupLayout btnContasAPagarLayout = new javax.swing.GroupLayout(btnContasAPagar);
        btnContasAPagar.setLayout(btnContasAPagarLayout);
        btnContasAPagarLayout.setHorizontalGroup(
            btnContasAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnContasAPagarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgContasAPagar)
                .addGap(20, 20, 20)
                .addComponent(lblContasAPagar)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        btnContasAPagarLayout.setVerticalGroup(
            btnContasAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgContasAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblContasAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnContasAPagar);

        btnRelatorioDeEstoque.setBackground(new java.awt.Color(12, 180, 206));
        btnRelatorioDeEstoque.setPreferredSize(new java.awt.Dimension(111, 40));
        btnRelatorioDeEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRelatorioDeEstoqueMousePressed(evt);
            }
        });

        imgRelatorioDeEstoque1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Shredder_25px.png"))); // NOI18N

        lblRelatorioDeEstoque1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRelatorioDeEstoque1.setForeground(new java.awt.Color(255, 255, 255));
        lblRelatorioDeEstoque1.setText("Relatório de Estoque");

        javax.swing.GroupLayout btnRelatorioDeEstoqueLayout = new javax.swing.GroupLayout(btnRelatorioDeEstoque);
        btnRelatorioDeEstoque.setLayout(btnRelatorioDeEstoqueLayout);
        btnRelatorioDeEstoqueLayout.setHorizontalGroup(
            btnRelatorioDeEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRelatorioDeEstoqueLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgRelatorioDeEstoque1)
                .addGap(20, 20, 20)
                .addComponent(lblRelatorioDeEstoque1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnRelatorioDeEstoqueLayout.setVerticalGroup(
            btnRelatorioDeEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRelatorioDeEstoque1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgRelatorioDeEstoque1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnRelatorioDeEstoque);

        btnRelatorioDeVendas.setBackground(new java.awt.Color(12, 180, 206));
        btnRelatorioDeVendas.setPreferredSize(new java.awt.Dimension(111, 40));
        btnRelatorioDeVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRelatorioDeVendasMousePressed(evt);
            }
        });

        imgRelatorioDeVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Print_25px.png"))); // NOI18N

        lblRelatorioDeVendas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRelatorioDeVendas.setForeground(new java.awt.Color(255, 255, 255));
        lblRelatorioDeVendas.setText("Relatório de Vendas");

        javax.swing.GroupLayout btnRelatorioDeVendasLayout = new javax.swing.GroupLayout(btnRelatorioDeVendas);
        btnRelatorioDeVendas.setLayout(btnRelatorioDeVendasLayout);
        btnRelatorioDeVendasLayout.setHorizontalGroup(
            btnRelatorioDeVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRelatorioDeVendasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgRelatorioDeVendas)
                .addGap(20, 20, 20)
                .addComponent(lblRelatorioDeVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnRelatorioDeVendasLayout.setVerticalGroup(
            btnRelatorioDeVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgRelatorioDeVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblRelatorioDeVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnRelatorioDeVendas);

        btnUsuario.setBackground(new java.awt.Color(12, 180, 206));
        btnUsuario.setPreferredSize(new java.awt.Dimension(111, 40));
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUsuarioMousePressed(evt);
            }
        });

        imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_More_Info_25px.png"))); // NOI18N

        lblUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario1.setText("Usuário");

        javax.swing.GroupLayout btnUsuarioLayout = new javax.swing.GroupLayout(btnUsuario);
        btnUsuario.setLayout(btnUsuarioLayout);
        btnUsuarioLayout.setHorizontalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgUsuario)
                .addGap(20, 20, 20)
                .addComponent(lblUsuario1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnUsuarioLayout.setVerticalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnUsuario);

        btnSac.setBackground(new java.awt.Color(12, 180, 206));
        btnSac.setPreferredSize(new java.awt.Dimension(111, 40));
        btnSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSacMousePressed(evt);
            }
        });

        imgSac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Ask_Question_25px.png"))); // NOI18N

        lblSac.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSac.setForeground(new java.awt.Color(255, 255, 255));
        lblSac.setText("Sac");

        javax.swing.GroupLayout btnSacLayout = new javax.swing.GroupLayout(btnSac);
        btnSac.setLayout(btnSacLayout);
        btnSacLayout.setHorizontalGroup(
            btnSacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSacLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgSac)
                .addGap(20, 20, 20)
                .addComponent(lblSac)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSacLayout.setVerticalGroup(
            btnSacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgSac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        atalhosDoMenu.add(btnSac);

        menuLateral.add(atalhosDoMenu, java.awt.BorderLayout.CENTER);

        btnSair.setBackground(new java.awt.Color(12, 180, 206));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSairMousePressed(evt);
            }
        });

        imgSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Sign_Out_25px.png"))); // NOI18N

        lblSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSair.setForeground(new java.awt.Color(255, 255, 255));
        lblSair.setText("Sair");

        javax.swing.GroupLayout btnSairLayout = new javax.swing.GroupLayout(btnSair);
        btnSair.setLayout(btnSairLayout);
        btnSairLayout.setHorizontalGroup(
            btnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSairLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgSair)
                .addGap(18, 18, 18)
                .addComponent(lblSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSairLayout.setVerticalGroup(
            btnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgSair, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
            .addComponent(lblSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuLateral.add(btnSair, java.awt.BorderLayout.PAGE_END);

        areaDeTrabalho.setBackground(new java.awt.Color(255, 255, 255));
        areaDeTrabalho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        painelBreadcrumb.setBackground(new java.awt.Color(102, 102, 102));

        lblBreadcrumb.setBackground(new java.awt.Color(204, 204, 204));
        lblBreadcrumb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBreadcrumb.setForeground(new java.awt.Color(238, 238, 238));
        lblBreadcrumb.setText("Estou na Tela de Produtos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuário:");

        jlUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlUsuarioLogado.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/status-de-login.png"))); // NOI18N

        javax.swing.GroupLayout painelBreadcrumbLayout = new javax.swing.GroupLayout(painelBreadcrumb);
        painelBreadcrumb.setLayout(painelBreadcrumbLayout);
        painelBreadcrumbLayout.setHorizontalGroup(
            painelBreadcrumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBreadcrumbLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(painelBreadcrumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(painelBreadcrumbLayout.createSequentialGroup()
                        .addComponent(lblBreadcrumb, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jlUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        painelBreadcrumbLayout.setVerticalGroup(
            painelBreadcrumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBreadcrumbLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelBreadcrumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBreadcrumb))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        lblNomeSistema.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNomeSistema.setForeground(new java.awt.Color(102, 102, 102));
        lblNomeSistema.setText("Sistema de Apoio ao Microempreendedor Individual");

        panelDinamic.setBackground(new java.awt.Color(255, 255, 255));
        panelDinamic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDinamic.setToolTipText("MayDay");
        panelDinamic.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Powered by Students of Estácio TV-Morena");

        jLdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(areaDeTrabalhoLayout.createSequentialGroup()
                .addGroup(areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areaDeTrabalhoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblNomeSistema)
                        .addGap(18, 18, 18)
                        .addComponent(jLdata, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLhora, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaDeTrabalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDinamic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(painelBreadcrumb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaDeTrabalhoLayout.createSequentialGroup()
                .addGroup(areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNomeSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaDeTrabalhoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLhora, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(jLdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(painelBreadcrumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDinamic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(areaDeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnSairMousePressed

    private void btnInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMousePressed
        VendaPrincipal exemplo = new VendaPrincipal();
        lblBreadcrumb.setText("BEM VINDO AO MEI");
        panelDinamic.removeAll();
        panelDinamic.add(exemplo);
        panelDinamic.validate();
        panelDinamic.repaint();
    }//GEN-LAST:event_btnInicioMousePressed

    private void btnUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Usuário", new UsuarioPrincipal());
    }//GEN-LAST:event_btnUsuarioMousePressed

    private void btnRelatorioDeEstoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioDeEstoqueMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Relatório de Estoque", new RelatorioDeEstoquePrincipal());
    }//GEN-LAST:event_btnRelatorioDeEstoqueMousePressed

    private void btnRelatorioDeVendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioDeVendasMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Relatório de Vendas", new RelatorioVendasPrincipal());
    }//GEN-LAST:event_btnRelatorioDeVendasMousePressed

    private void btnProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Cadastro de Produtos", new ProdutoPrincipal());
    }//GEN-LAST:event_btnProdutosMousePressed

    private void btnVendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendasMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Gerenciamento de Vendas", new VendaPrincipal());
    }//GEN-LAST:event_btnVendasMousePressed

    private void btnComprasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprasMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Gerenciamento de Compras", new CompraPrincipal());
    }//GEN-LAST:event_btnComprasMousePressed

    private void btnFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFornecedorMousePressed

        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Gerenciamento de Fornecedor", new FornecedorPrincipal());
    }//GEN-LAST:event_btnFornecedorMousePressed

    private void btnClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Gerenciamento de Clientes", new ClientePrincipal());
    }//GEN-LAST:event_btnClientesMousePressed

    private void btnCategoriasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Gerenciamento de Categoria ", new CategoriaPrincipal());
    }//GEN-LAST:event_btnCategoriasMousePressed

    private void btnContasAReceberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContasAReceberMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Contas a Receber", new ContasAReceberPrincipal());
    }//GEN-LAST:event_btnContasAReceberMousePressed

    private void btnContasAPagarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContasAPagarMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Contas a Pagar", new ContasAPagarPrincipal());
    }//GEN-LAST:event_btnContasAPagarMousePressed

    private void btnSacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSacMousePressed
        resetColor((JPanel) panelActive);
        panelActive = evt.getSource();
        updatePanelDinamic("Sac", new SacPrincipal());
    }//GEN-LAST:event_btnSacMousePressed

    private void hoverEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverEntered
        /*  
            Primeiro faço uma verificação de segurança se a origem (fonte)
            do evento é realmente um JPanel
            Isso foi feito pois estou usando o mesmo evento para todos os 
            itens do menu.
         */
        if (evt.getSource() instanceof JPanel) {
            /*  O método getSource retorna um Object, por isso faço a conversão (cast)
                para JPanel
             */
            JPanel panel = (JPanel) evt.getSource();
            /*  o método change color recebe como parâmetro um JPanel e faz a 
                mudança de cores, subistitui o setColor (já existe esse método na 
                classe Jframe)
             */
            changeColor(panel);
        }
    }//GEN-LAST:event_hoverEntered

    private void hoverExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverExited
        if (evt.getSource() instanceof JPanel && !evt.getSource().equals(panelActive)) {
            JPanel panel = (JPanel) evt.getSource();
            resetColor(panel);
        }
    }//GEN-LAST:event_hoverExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        Date dataSistema = new Date();
        SimpleDateFormat formato =  new SimpleDateFormat("dd 'de' MMMM 'de' yyyy");
        jLdata.setText(formato.format(dataSistema));
        
        Timer timer = new Timer(1000, new hora());
        timer.start();
        
    }//GEN-LAST:event_formWindowOpened

    private void updateColorActive(MouseEvent evt) {
        Component[] components = evt.getComponent().getParent().getComponents();
        for (Component component : components){
            if(component instanceof JPanel){
                if(component.equals(evt.getSource()))
                    changeColor((JPanel)component);
                else
                    resetColor((JPanel)component);
            }
        }
    }
    

    private void updatePanelDinamic(String label, JPanel panel) {
        lblBreadcrumb.setText(label);
        panelDinamic.removeAll();
        panelDinamic.add(panel);
        panelDinamic.validate();
        panelDinamic.repaint();

    }

    public void changeColor(JPanel panelHovered) {
        panelHovered.setBackground(new Color(44, 197, 221));
    }

    public void resetColor(JPanel panelHovered) {
        panelHovered.setBackground(new Color(12, 180, 206));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaDeTrabalho;
    private javax.swing.JPanel atalhosDoMenu;
    private javax.swing.JPanel btnCategorias;
    private javax.swing.JPanel btnClientes;
    private javax.swing.JPanel btnCompras;
    private javax.swing.JPanel btnContasAPagar;
    private javax.swing.JPanel btnContasAReceber;
    private javax.swing.JPanel btnFornecedor;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnProdutos;
    private javax.swing.JPanel btnRelatorioDeEstoque;
    private javax.swing.JPanel btnRelatorioDeVendas;
    private javax.swing.JPanel btnSac;
    private javax.swing.JPanel btnSair;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JPanel btnVendas;
    private javax.swing.JPanel iconeSistema;
    private javax.swing.JLabel imgCadastroDeProdutos;
    private javax.swing.JLabel imgCategorias;
    private javax.swing.JLabel imgClientes;
    private javax.swing.JLabel imgCompras;
    private javax.swing.JLabel imgContasAPagar;
    private javax.swing.JLabel imgContasAReceber;
    private javax.swing.JLabel imgFornecedores;
    private javax.swing.JLabel imgInicio;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgRelatorioDeEstoque1;
    private javax.swing.JLabel imgRelatorioDeVendas;
    private javax.swing.JLabel imgSac;
    private javax.swing.JLabel imgSair;
    private javax.swing.JLabel imgUsuario;
    private javax.swing.JLabel imgVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLdata;
    private javax.swing.JLabel jLhora;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlUsuarioLogado;
    private javax.swing.JLabel lblBreadcrumb;
    private javax.swing.JLabel lblCadastroDeProdutos;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCompras;
    private javax.swing.JLabel lblContasAPagar;
    private javax.swing.JLabel lblContasAReceber;
    private javax.swing.JLabel lblFornecedores;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblNomeSistema;
    private javax.swing.JLabel lblRelatorioDeEstoque1;
    private javax.swing.JLabel lblRelatorioDeVendas;
    private javax.swing.JLabel lblSac;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel painelBreadcrumb;
    private javax.swing.JPanel panelDinamic;
    // End of variables declaration//GEN-END:variables
    private Object panelActive;
    
    class hora implements ActionListener{
    @Override
    public void actionPerformed(ActionEvent e){
        Calendar now = Calendar.getInstance();
        jLhora.setText(String.format("%1$tH:%1$tM:%1$tS",now));
    }
    
    }
    
}
