/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.estacio.mei.visao.relatorio.estoque;

import br.estacio.mei.dao.ProdutoDao;
import br.estacio.mei.dao.implementacao.ProdutoDaoEstatico;
import br.estacio.mei.model.Fornecedor;
import br.estacio.mei.model.Produto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo
 */
public class RelatorioDeEstoquePrincipal extends javax.swing.JPanel {
    ProdutoDao produtoDao = new ProdutoDaoEstatico();
    /**
     * Creates new form RelatorioDeEstoque
     */
    public RelatorioDeEstoquePrincipal() {
        initComponents();
        
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setRazaoSocial("Estacio");
        Produto produto = new Produto(0, "Camisa", 10, fornecedor, 10, 20);
        produtoDao.salvar(produto);
        
        produto = new Produto(1, "Short", 5, fornecedor, 40, 80);
        
        produtoDao.salvar(produto);
        
        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel)tbProdutos.getModel();

        ArrayList<Produto> listaDeProdutos = produtoDao.buscarProdutos();
        for (int i=0; i< listaDeProdutos.size();i++)
        {
            Produto p = listaDeProdutos.get(i);
            Object[] dadosDaLinha = new Object[6];
            dadosDaLinha[0] = p.getCodigo();
            dadosDaLinha[1] = p.getNome();
            dadosDaLinha[2] = p.getFornecedor().getRazaoSocial();
            dadosDaLinha[3] = p.getPrecoCompra();
            dadosDaLinha[4] = p.getPrecoVenda();
            dadosDaLinha[5] = p.getQuantidade();
            modeloDeColunasDaTabela.addRow(dadosDaLinha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPesquisar = new javax.swing.JTextPane();
        btnPesquisar = new javax.swing.JButton();
        jButtonNovoProduto = new javax.swing.JButton();
        tipoPesquisa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        lblResultado = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        txtPesquisar.setToolTipText("");
        txtPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(txtPesquisar);

        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jButtonNovoProduto.setText("Novo Produto");
        jButtonNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoProdutoActionPerformed(evt);
            }
        });

        tipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Fornecedor", "Preço de Compra", "Preço de Venda", "Qtde Estoque" }));
        tipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(tipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonNovoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addGap(50, 50, 50))
        );

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Fornecedor", "Preço de Compra", "Preço de Venda", "Qtde Estoque"
            }
        ));
        jScrollPane1.setViewportView(tbProdutos);

        lblResultado.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(lblResultado)
                .addContainerGap(368, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addGap(20, 20, 20)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblResultado)
                .addGap(0, 709, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoProdutoActionPerformed
        int linha = tbProdutos.getSelectedRow();
        int codigo = (int)tbProdutos.getModel().getValueAt(linha, 0);
        lblResultado.setText(""+codigo);
    }//GEN-LAST:event_jButtonNovoProdutoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int itemSelecionado = tipoPesquisa.getSelectedIndex();
        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel)tbProdutos.getModel();
        switch(itemSelecionado) {
            case 0:
                    int pesqCodigo = Integer.parseInt(txtPesquisar.getText());
                    while (modeloDeColunasDaTabela.getRowCount() != 0) {
                        modeloDeColunasDaTabela.removeRow(0);
                    }
                    ArrayList<Produto> produtosPorCodigo = produtoDao.pesquisarPorCodigo(pesqCodigo);
                    for (int i=0; i< produtosPorCodigo.size();i++)
                    {
                        Produto p = produtosPorCodigo.get(i);
                        Object[] dadosDaLinha = new Object[6];
                        dadosDaLinha[0] = p.getCodigo();
                        dadosDaLinha[1] = p.getNome();
                        dadosDaLinha[2] = p.getFornecedor().getRazaoSocial();
                        dadosDaLinha[3] = p.getPrecoCompra();
                        dadosDaLinha[4] = p.getPrecoVenda();
                        dadosDaLinha[5] = p.getQuantidade();
                        modeloDeColunasDaTabela.addRow(dadosDaLinha);
                    }
                    break;
            case 1:
                    String pesqNome = txtPesquisar.getText();
                    while (modeloDeColunasDaTabela.getRowCount() != 0) {
                        modeloDeColunasDaTabela.removeRow(0);
                    }
                    System.out.println("pesqNome");
                    ArrayList<Produto> produtosPorNome = produtoDao.pesquisarPorNome(pesqNome);
                    for (int i=0; i< produtosPorNome.size();i++)
                    {
                        Produto p = produtosPorNome.get(i);
                        Object[] dadosDaLinha = new Object[6];
                        dadosDaLinha[0] = p.getCodigo();
                        dadosDaLinha[1] = p.getNome();
                        dadosDaLinha[2] = p.getFornecedor().getRazaoSocial();
                        dadosDaLinha[3] = p.getPrecoCompra();
                        dadosDaLinha[4] = p.getPrecoVenda();
                        dadosDaLinha[5] = p.getQuantidade();
                        modeloDeColunasDaTabela.addRow(dadosDaLinha);
                    }
                    break;
            case 2:
                    String pesqFornecedor = txtPesquisar.getText();
                    while (modeloDeColunasDaTabela.getRowCount() != 0) {
                        modeloDeColunasDaTabela.removeRow(0);
                    }
                    ArrayList<Produto> produtosPorFornecedor = produtoDao.pesquisarPorNome(pesqFornecedor);
                    for (int i=0; i< produtosPorFornecedor.size();i++)
                    {
                        Produto p = produtosPorFornecedor.get(i);
                        Object[] dadosDaLinha = new Object[6];
                        dadosDaLinha[0] = p.getCodigo();
                        dadosDaLinha[1] = p.getNome();
                        dadosDaLinha[2] = p.getFornecedor().getRazaoSocial();
                        dadosDaLinha[3] = p.getPrecoCompra();
                        dadosDaLinha[4] = p.getPrecoVenda();
                        dadosDaLinha[5] = p.getQuantidade();
                        modeloDeColunasDaTabela.addRow(dadosDaLinha);
                    }
                    break;
            case 3:
                    int pesqPrecoCompra = Integer.parseInt(txtPesquisar.getText());
                    while (modeloDeColunasDaTabela.getRowCount() != 0) {
                        modeloDeColunasDaTabela.removeRow(0);
                    }
                    ArrayList<Produto> produtosPorPrecoCompra = produtoDao.pesquisarPorPrecoCompra(pesqPrecoCompra);
                    for (int i=0; i< produtosPorPrecoCompra.size();i++)
                    {
                        Produto p = produtosPorPrecoCompra.get(i);
                        Object[] dadosDaLinha = new Object[6];
                        dadosDaLinha[0] = p.getCodigo();
                        dadosDaLinha[1] = p.getNome();
                        dadosDaLinha[2] = p.getFornecedor().getRazaoSocial();
                        dadosDaLinha[3] = p.getPrecoCompra();
                        dadosDaLinha[4] = p.getPrecoVenda();
                        dadosDaLinha[5] = p.getQuantidade();
                        modeloDeColunasDaTabela.addRow(dadosDaLinha);
                    }
                    break;
            case 4:
                    int pesqPrecoVenda = Integer.parseInt(txtPesquisar.getText());
                    while (modeloDeColunasDaTabela.getRowCount() != 0) {
                        modeloDeColunasDaTabela.removeRow(0);
                    }
                    ArrayList<Produto> produtosPorPrecoVenda = produtoDao.pesquisarPorPrecoVenda(pesqPrecoVenda);
                    for (int i=0; i< produtosPorPrecoVenda.size();i++)
                    {
                        Produto p = produtosPorPrecoVenda.get(i);
                        Object[] dadosDaLinha = new Object[6];
                        dadosDaLinha[0] = p.getCodigo();
                        dadosDaLinha[1] = p.getNome();
                        dadosDaLinha[2] = p.getFornecedor().getRazaoSocial();
                        dadosDaLinha[3] = p.getPrecoCompra();
                        dadosDaLinha[4] = p.getPrecoVenda();
                        dadosDaLinha[5] = p.getQuantidade();
                        modeloDeColunasDaTabela.addRow(dadosDaLinha);
                    }
                    break;
            case 5:
                    int pesqQtdEstoque = Integer.parseInt(txtPesquisar.getText());
                    while (modeloDeColunasDaTabela.getRowCount() != 0) {
                        modeloDeColunasDaTabela.removeRow(0);
                    }
                    ArrayList<Produto> produtosPorQtdEstoque = produtoDao.pesquisarPorQtdEstoque(pesqQtdEstoque);
                    for (int i=0; i< produtosPorQtdEstoque.size();i++)
                    {
                        Produto p = produtosPorQtdEstoque.get(i);
                        Object[] dadosDaLinha = new Object[6];
                        dadosDaLinha[0] = p.getCodigo();
                        dadosDaLinha[1] = p.getNome();
                        dadosDaLinha[2] = p.getFornecedor().getRazaoSocial();
                        dadosDaLinha[3] = p.getPrecoCompra();
                        dadosDaLinha[4] = p.getPrecoVenda();
                        dadosDaLinha[5] = p.getQuantidade();
                        modeloDeColunasDaTabela.addRow(dadosDaLinha);
                    }
                    break;
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButtonNovoProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JComboBox<String> tipoPesquisa;
    private javax.swing.JTextPane txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
